fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    mysql: git://github.com/puppetlabs/puppetlabs-mysql.git
    postgresql: git://github.com/puppetlabs/puppetlabs-postgresql.git
    staging: git://github.com/puppetlabs/nanliu-staging.git
    epel: git://github.com/puppetlabs/puppetlabs-epel.git
  symlinks:
    cloudera: "#{source_dir}"
